-- MySQL Script generated by MySQL Workbench
-- Mon Feb  3 14:27:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`flyway_schema_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flyway_schema_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flyway_schema_history` (
  `installed_rank` INT(11) NOT NULL,
  `version` VARCHAR(50) NULL DEFAULT NULL,
  `description` VARCHAR(200) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `script` VARCHAR(1000) NOT NULL,
  `checksum` INT(11) NULL DEFAULT NULL,
  `installed_by` VARCHAR(100) NOT NULL,
  `installed_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `execution_time` INT(11) NOT NULL,
  `success` TINYINT(1) NOT NULL,
  PRIMARY KEY (`installed_rank`),
  INDEX `flyway_schema_history_s_idx` (`success` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`hibernate_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hibernate_sequence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_address` (
  `pk_address_id` INT(11) NOT NULL AUTO_INCREMENT,
  `flatname` VARCHAR(45) NULL DEFAULT NULL,
  `flatnumber` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `area` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `pincode` VARCHAR(45) NULL DEFAULT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk_address_id`),
  UNIQUE INDEX `pk_address_id_UNIQUE` (`pk_address_id` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_hospital` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_hospital` (
  `pk_hospital_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk_hospital_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_branch` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_branch` (
  `pk_branch_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `fk_hospital_id` INT(11) NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fk_address_id` INT(11) NOT NULL,
  PRIMARY KEY (`pk_branch_id`),
  UNIQUE INDEX `fk_address_id_UNIQUE` (`fk_address_id` ASC),
  INDEX `fk_hospital_id_idx` (`fk_hospital_id` ASC) ,
  CONSTRAINT `fk_address_id_branch`
    FOREIGN KEY (`fk_address_id`)
    REFERENCES `mydb`.`t_address` (`pk_address_id`),
  CONSTRAINT `fk_hospital_id`
    FOREIGN KEY (`fk_hospital_id`)
    REFERENCES `mydb`.`t_hospital` (`pk_hospital_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_role` (
  `pk_role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk_role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user` (
  `pk_user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `fk_role_id` INT(11) NOT NULL DEFAULT '0',
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fk_address_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`pk_user_id`),
  INDEX `pk_role_id_idx` (`fk_role_id` ASC) ,
  INDEX `fk_address_id_idx` (`fk_address_id` ASC) ,
  CONSTRAINT `fk_address_id`
    FOREIGN KEY (`fk_address_id`)
    REFERENCES `mydb`.`t_address` (`pk_address_id`),
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`fk_role_id`)
    REFERENCES `mydb`.`t_role` (`pk_role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_admin` (
  `pk_admin_id` INT(11) NOT NULL,
  `fk_user_id` INT(11) NOT NULL,
  `fk_branch_id` INT(11) NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk_admin_id`),
  UNIQUE INDEX `fk_user_id_UNIQUE` (`fk_user_id` ASC) ,
  INDEX `fk_user_id_idx` (`fk_user_id` ASC) ,
  INDEX `fk_branch_id_idx` (`fk_branch_id` ASC) ,
  CONSTRAINT `fk_branch_id`
    FOREIGN KEY (`fk_branch_id`)
    REFERENCES `mydb`.`t_branch` (`pk_branch_id`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`t_user` (`pk_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_doctor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_doctor` (
  `pk_doctor_id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `qualification` VARCHAR(45) NULL DEFAULT NULL,
  `fk_user_id` INT(10) UNSIGNED NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk_doctor_id`),
  UNIQUE INDEX `pk_doctor_id_UNIQUE` (`pk_doctor_id` ASC) ,
  UNIQUE INDEX `fk_user_id_UNIQUE` (`fk_user_id` ASC) ,
  INDEX `fk_user_id_idx` (`fk_user_id` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_doctor_branch_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_doctor_branch_mapping` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_doctor_branch_mapping` (
  `fk_doctor_id` INT(11) NOT NULL,
  `fk_branch_id` INT(11) NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fk_doctor_id`, `fk_branch_id`),
  INDEX `branch_id_idx` (`fk_branch_id` ASC) ,
  CONSTRAINT `fk_branch_id_doctor`
    FOREIGN KEY (`fk_branch_id`)
    REFERENCES `mydb`.`t_branch` (`pk_branch_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_doctor_id_branch`
    FOREIGN KEY (`fk_doctor_id`)
    REFERENCES `mydb`.`t_doctor` (`pk_doctor_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_patient` (
  `pk_patient_id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `blood_group` VARCHAR(4) NULL DEFAULT NULL,
  `fk_user_id` INT(11) NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk_patient_id`),
  INDEX `fk_user_id_idx` (`fk_user_id` ASC) ,
  CONSTRAINT `fk_user_id_patient`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`t_user` (`pk_user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_patient_branch_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_patient_branch_mapping` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_patient_branch_mapping` (
  `patient_id` INT(11) NOT NULL,
  `branch_id` INT(11) NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`patient_id`, `branch_id`),
  INDEX `branch_id_idx` (`branch_id` ASC) ,
  CONSTRAINT `fk_branch_id_patient`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`t_branch` (`pk_branch_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_patient_id_branch`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`t_patient` (`pk_patient_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`t_patient_doctor_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_patient_doctor_mapping` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_patient_doctor_mapping` (
  `fk_patient_id` INT(11) NOT NULL,
  `fk_doctor_id` INT(11) NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `pk_patient_doctor_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pk_patient_doctor_id`),
  UNIQUE INDEX `pk_patient_doctor_id_UNIQUE` (`pk_patient_doctor_id` ASC),
  UNIQUE INDEX `UK_nad5ll7k2dvi649upq7o8hieu` (`fk_patient_id` ASC) ,
  INDEX `doctor_id_idx` (`fk_doctor_id` ASC) ,
  CONSTRAINT `fk_doctor_id`
    FOREIGN KEY (`fk_doctor_id`)
    REFERENCES `mydb`.`t_doctor` (`pk_doctor_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_pateint_id`
    FOREIGN KEY (`fk_patient_id`)
    REFERENCES `mydb`.`t_patient` (`pk_patient_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
